"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ  # <-- 1. Importamos django-environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# 2. Inicializamos environ
env = environ.Env(
    DEBUG=(bool, False)
)

# 3. Leemos el archivo .env desde la raíz del proyecto
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# core/settings.py

# ==========================================
# CONFIGURACIONES DE ENTORNO (PRODUCCIÓN / LOCAL)
# ==========================================

SECRET_KEY = env('SECRET_KEY', default='django-insecure-7ydfe!tw)0i#q5ntb$qldct=r38)k)=xs&4-71xr=l3&3wxyq!')

DEBUG = env('DEBUG')

# Agregamos TODAS las opciones juntas directamente en la lista.
# Así funcionará en tu computadora local y en Render al mismo tiempo sin depender de nada más.
ALLOWED_HOSTS = [
    'biblioteca-api-nello.onrender.com',
    '127.0.0.1',
    'localhost',
    '*'  # El comodín definitivo por si Render usa proxies internos
]
# ==========================================
# CONFIGURACIONES EXTRAÍDAS DEL .ENV
# ==========================================

# 4. Reemplazamos los valores planos por las variables del entorno
SECRET_KEY = env('SECRET_KEY')

DEBUG = env('DEBUG')

# 1. Leemos el valor como texto plano (String) del entorno
allowed_hosts_raw = env('ALLOWED_HOSTS', default='127.0.0.1,localhost')

# 2. Lo dividimos dinámicamente por comas y limpiamos espacios fantasmas
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.split(',') if host]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7ydfe!tw)0i#q5ntb$qldct=r38)k)=xs&4-71xr=l3&3wxyq!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de Terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    
    # Apps Propias
    'biblioteca',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    # Forzar a que por defecto todo Endpoint pida autenticación (Buenas prácticas de seguridad)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Configurar drf-spectacular como el generador de esquema de documentación
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Configuración de la documentación de Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'API de Biblioteca Virtual',
    'DESCRIPTION': 'API robusta para la gestión de libros, autores y préstamos.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Añadir soporte para JWT en la interfaz de Swagger
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'JWT': []}],
}